### ISSUE TITLE
tensorflow with windows issue and python 2.7

### ISSUE THREAD

**Issue by Tsardoz** [bmcmenamin/fa_kit#1]
pip install fa_kit
leads to error
"Could not find a version that satisfies the requirement tensorflow"
Google search problem yields:

https://www.tensorflow.org/install/install_windows
"TensorFlow supports Python 3.5.x and 3.6.x on Windows"

Since TensorFlow requires Python 3.5 or 3.6 fa_kit will not install on Windows/Python 2.7. It would be preferable if tensorflow was omitted in this case from a Windows/Python 2.7 user perspective.

I ended up installing Anaconda 3.6 and it works but all my other scripts are in 2.7.

**Comment by bmcmenamin** [comment]
i didn't know that there was a python2/tensorflow conflict on windows, so for now I'll make a note in the readme and work on separating making the tensorflow dependancy optional

**Comment by bmcmenamin** [comment]
the new version on PyPI (0.1.2) should allow you to install without tensorflow.

i'm a total n00b at pypi, so let me know if i screwed something up in the release.
